[package]
name = "pacrs"
version = "0.1.0"
edition = "2021"

[dependencies]
alpm = "4.0.1"
alpm-utils = "4.0.1"
anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive"] }
fs-err = "3.0.0"
humansize = "2.1.3"
pacmanconf = "3.0.0"
raur = "7.0.0"
tokio = { version = "1.41.1", features = ["full"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
strip = "symbols"
